### PR TITLE
created readme

### PR DESCRIPTION
**Pull request by BBK-SDP-2015-emassa01**

### CODE REVIEW

**Comment by BBK-SDP-2015-lstefa01** [comment]
thanks

**Comment by BBK-SDP-2015-lstefa01** [comment]
Hey,

I pushed a few minor changes to the tests. Now my brain is not in fog, I
created a little loop to initialise a full board. I also added a check if
depth is 0, to set it automatically to 1 without throwing an exception(as I
was not sure about changing the guy class to handle that exception)

Please merge on your side if you are ok with these

Also, I added the git repo to be cloned to my dropbox saying it was the
work of both of us. I advise you to do the same, just in case :)

Speak to you soon...

**Comment by BBK-SDP-2015-emassa01** [comment]
Hey Liliya
Thanks, I merged.

I think this is wrong (in the AI class)
+ if depth ==0
depth = 1; println("No depth of 0 allowed - depth set to default of 1")

As he didnt tell us to do this, I think we should just throw an exception.
The thing I'm worried about is that there is some non-randomness with a
depth of 1
​,​
right
​, when there should be either no move, or a random move (a completely
stupid random ai).
​

Do you think when he tests our methods with various values, the output will
be wrong, i.e., the result of the method is not random with a depth of 0?)

I think we could just have it throw an exception instead?

​Currently with a depth of 0 the exception in Move throws a message to the
user
"cannot make a move until a move is produced" do you think this is better
than assuming a depth of 1 instead of 0?​



__________________________________________________________________
Esha Massand
Postdoctoral Research Fellow
Centre for Brain & Cognitive Development, Department of Psychological
Sciences
Birkbeck, University of London, 32 Torrington Square, London WC1E 7HX, U.K.
t: +44 (0)20 7079 0778
lab website: http://www.cbcd.bbk.ac.uk/people

LonDownS Infant Stream Website:
http://www.ucl.ac.uk/london-down-syndrome-consortium/research-themes/infants


*"You can't score a goal without goal-posts".*
__________________________________________________________________

**Comment by BBK-SDP-2015-lstefa01** [comment]
Hey,

Currently you would get an NullPointerException anyway and we are not
handling it anyhow

I am completely open to change it if there is a better approach

**Comment by BBK-SDP-2015-emassa01** [comment]
hey have a look in runGame method in Game

if (bestMoves.length == 0) {

          gui.setMsg("Game cannot continue until a Move is produced.")


What about this?





__________________________________________________________________
Esha Massand
Postdoctoral Research Fellow
Centre for Brain & Cognitive Development, Department of Psychological
Sciences
Birkbeck, University of London, 32 Torrington Square, London WC1E 7HX, U.K.
t: +44 (0)20 7079 0778
lab website: http://www.cbcd.bbk.ac.uk/people

LonDownS Infant Stream Website:
http://www.ucl.ac.uk/london-down-syndrome-consortium/research-themes/infants


*"You can't score a goal without goal-posts".*
__________________________________________________________________

**Comment by BBK-SDP-2015-lstefa01** [comment]
No, this exception is only if for some reason no move is returned, it does
not seem to take care of the tree not generating in the first place

The way I see it, the correct way to handle will be to throw an exception
from the getMoves method if depth is 0 and have the run game method catch
it and show it in the gui. But as we cannot change the Game class, I was
not sure how else we can handle, other than just throw the exception and
have it kill the program.

**Comment by BBK-SDP-2015-emassa01** [comment]
When I run the GUI with 2 AI's initialised with depth '0', the runGame
method sends a message to the GUI as getMoves in AI return an array of
length 0
The the message to the GUI that is thrown "Game cannot continue until a
Move is produced"

Are you suggesting we also throw an exception at this point? Happy to work
with that, just not happy with setting the depth to 1 as I think that may
be something beyond the description in the document he gave us?


AI getMoves currently includes:

  //if depth is 0 - Exception not thrown up to GUI as we were instructed to
not change the Game class

    if (depth == 0) {

      depth = 1; println("No depth of 0 allowed - depth set to default of 1"
)

    }


can we not assume a depth of one, but throw an exception (like you said) so
change it to


  //if depth is 0 - Exception not thrown up to GUI as we were instructed to
not change the Game class

    if (depth == 0) {

throw new IllegalArgumentException("No depth of 0 allowed - depth set to
default of 1")

    }


Thanks?


__________________________________________________________________
Esha Massand
Postdoctoral Research Fellow
Centre for Brain & Cognitive Development, Department of Psychological
Sciences
Birkbeck, University of London, 32 Torrington Square, London WC1E 7HX, U.K.
t: +44 (0)20 7079 0778
lab website: http://www.cbcd.bbk.ac.uk/people

LonDownS Infant Stream Website:
http://www.ucl.ac.uk/london-down-syndrome-consortium/research-themes/infants


*"You can't score a goal without goal-posts".*
__________________________________________________________________

**Comment by BBK-SDP-2015-lstefa01** [comment]
Ah, ok, if this works then that's ok

For me when I ran one of the AI's with depth 0 I get the IDE throwing null
pointer exception

**Comment by BBK-SDP-2015-emassa01** [comment]
OK thanks
Shall I check/change /push it?


__________________________________________________________________
Esha Massand
Postdoctoral Research Fellow
Centre for Brain & Cognitive Development, Department of Psychological
Sciences
Birkbeck, University of London, 32 Torrington Square, London WC1E 7HX, U.K.
t: +44 (0)20 7079 0778
lab website: http://www.cbcd.bbk.ac.uk/people

LonDownS Infant Stream Website:
http://www.ucl.ac.uk/london-down-syndrome-consortium/research-themes/infants


*"You can't score a goal without goal-posts".*
__________________________________________________________________

**Comment by BBK-SDP-2015-lstefa01** [comment]
OK

**Comment by BBK-SDP-2015-emassa01** [comment]
Please let me know what you think.
Thanks
Esha

**Pull request merged**
